# This workflow is based on the starter template at https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml.
# It will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: uv_lexos

# I think that this will perform CI on _any_ branch whenever there is a push or pull request.
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        uv-version: ["0.7.4"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv # Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5 # actions/setup-python@v3
      with:
        version: ${{ matrix.uv-version }}
        # python-version: ${{ matrix.python-version }}
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install the project
      run: uv sync --locked --all-extras --dev

    # The block below may not be right. See https://docs.astral.sh/uv/guides/integration/github/#caching
    # - name: Define a cache dependency glob
    #   uses: astral-sh/setup-uv@v5
    #   with:
    #     enable-cache: true
    #     cache-dependency-glob: "uv.lock"

    # The block below should be changed to lint with ruff, but that is not a current dev dependency, so it is disabled for the moment in this config file.
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest