site_name: Lexos Documentation
site_dir: "../docs"
site_url: https://lexos.github.io/en/latest/

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
      - Overview: user_guide/index.md
      - Getting Started: user_guide/getting_started.md
      - Loading Texts: user_guide/loading_texts.md
      - Proprocessing Steps:
        - Overview: user_guide/preprocessing_steps.md
        - Scrubbing Texts:
          - Scrubber Overview: user_guide/scrubbing_texts.md
          - Normalize: user_guide/scrubber/normalize.md
          - Remove: user_guide/scrubber/remove.md
          - Replace: user_guide/scrubber/replace.md
          - Tags: user_guide/scrubber/tags.md
          - Internal Components: user_guide/scrubber/internal_components.md
        - Tokenizing Texts: user_guide/tokenizing_texts.md
        - Cutting Documents: user_guide/cutting_documents.md
        - Cutting Bracken: user_guide/cutting_bracken.md
      - The Document-Term Matrix: user_guide/the_document_term_matrix.md
      - Visualization: user_guide/visualization.md
      - Managing a Corpus: user_guide/managing_a_corpus.md
      - Analyzing Documents:
        - Overview: user_guide/analyzing_documents.md
        - Clustering:
          - Overview: user_guide/clustering.md
          - Hierarchical Agglomerative Clustering: user_guide/cluster/hierarchical-agglomerative-clustering.md
          - K-Means Cluster Analysis: user_guide/cluster/k-means.md
        - Rolling Windows: user_guide/rolling_windows.md
        - Topwords: user_guide/topwords.md
        - Keywords in Context (KWIC): user_guide/kwic.md
  #     - Training a Language Model: user_guide/training_a_language_model.md
  #     - Topic Modelling with MALLET: user_guide/mallet_topic_models.md
  - Tutorials:
      - Overview: tutorials/index.md
  - API:
      - Overview: api/index.md
      - cluster:
          - Overview: api/cluster/index.md
          - kmeans: api/cluster/kmeans.md
      - corpus:
          - Corpus: api/corpus/index.md
      - cutter:
          - Cutter: api/cutter/index.md
      - dtm:
          - Overview: api/dtm/index.md
          - dtm: api/dtm/dtm.md
      - filter:
          - Overview: api/filters/index.md
          - filters: api/filters/filters.md
      - io:
          - Overview: api/io/index.md
          - base_loader: api/io/base_loader.md
          - loader: api/io/loader.md
          - data_loader: api/io/dataloader.md
      - milestones:
          - Overview: api/milestones/overview.md
          - span_milestones: api/milestones/span_milestones.md
          - string_milestones: api/milestones/string_milestones.md
          - token_milestones: api/milestones/token_milestones.md
          - util: api/milestones/util.md
      - rolling_windows:
          - Overview: api/rolling_windows/index.md
          - rolling_windows: api/rolling_windows/rolling_windows.md
          - calculators:
              - Overview: api/rolling_windows/calculators/index.md
              - averages: api/rolling_windows/calculators/averages.md
              - base_calculator: api/rolling_windows/calculators/base_calculator.md
              - counts: api/rolling_windows/calculators/counts.md
              - ratios: api/rolling_windows/calculators/ratios.md
          - plotters:
              - Overview: api/rolling_windows/plotters/index.md
              - base_plotter: api/rolling_windows/plotters/base_plotter.md
              - plotly_plotter: api/rolling_windows/plotters/plotly_plotter.md
              - simple_plotter: api/rolling_windows/plotters/simple_plotter.md
  #     - Language_Model:
  #         - Language_Model: api/language_model/index.md
      - scrubber:
          - Overview: api/scrubber/index.md
          - normalize: api/scrubber/normalize.md
          - pipeline: api/scrubber/pipeline.md
          - registry: api/scrubber/registry.md
          - remove: api/scrubber/remove.md
          - replace: api/scrubber/replace.md
          - resources: api/scrubber/resources.md
          - scrubber: api/scrubber/scrubber.md
          - tags: api/scrubber/tags.md
          - utils: api/scrubber/utils.md
  #     - Topic_Model:
  #         - Topic_Model: api/topic_model/index.md
      - tokenizer:
          - Overview: api/tokenizer/index.md
          - tokenizer: api/tokenizer/tokenizer.md
          - ngrams: api/tokenizer/ngrams.md
  #         - LexosDoc: api/tokenizer/lexosdoc.md
  #     - Visualization:
  #         - Overview: api/visualization/index.md
  #         - Bubbleviz: api/visualization/bubbleviz.md
  #         - Cloud: api/visualization/wordcloud.md
  #         - Plotly: api/visualization/plotly.md
  #         - Seaborn: api/visualization/seaborn.md
  #     - Utils: api/utils.md
      - topic_modeling:
          - Overview: api/topic_modeling/index.md
          - dfr_browser:
            - Overview: api/topic_modeling/dfr_browser/index.md
            - dfr_browser: api/topic_modeling/dfr_browser/dfr_browser.md
            - prepare_data: api/topic_modeling/dfr_browser/prepare_data.md
            - scale_model: api/topic_modeling/dfr_browser/scale_model.md
          - mallet: api/topic_modeling/mallet.md
      - visualization:
          - Overview: api/visualization/index.md
          - bubbleviz: api/visualization/bubbleviz.md
          - cloud: api/visualization/cloud.md
          - plotly_wordcloud: api/visualization/plotly_wordcloud.md
          - processors: api/visualization/processors.md
  - Development:
      - Overview: development/index.md

theme:
  name: material
  favicon: http://lexos.wheatoncollege.edu/static/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  # logo: images/lexos_logo.png
  custom_dir: overrides
  language: en
  # search: true
  features:
    # - navigation.tabs
    - navigation.top
    - navigation.indexes
  icon:
    logo: lexos/dragon
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  # - meta
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.keys
  - attr_list
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      permalink: "¤"

copyright: Copyright &copy; 2022- <a href="https://wheatoncollege.edu/academics/special-projects-initiatives/lexomics/" target="_blank">The Lexomics Project</a>

repo_url: https://github.com/scottkleinman/lexos

extra_css:
  - stylesheets/extra.css

# extra_javascript:
# - https://code.jquery.com/jquery-3.6.0.slim.min.js
# - javascripts/mark.es6.min.js

extra:
  social:
    - icon: fontawesome/solid/globe
      link: http://lexos.wheatoncollege.edu/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/Lexomics
    - icon: fontawesome/brands/github
      link: https://github.com/scottkleinman/uv_lexos/
  analytics:
    provider: google
    property: G-S7XYDZ16KZ

plugins:
  - search
  - git-revision-date-localized # For GitHub Actions, see https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-systems-like-github-actions
  - autorefs
  - section-index
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            # docstring_options:
            #   ignore_init_summary: true
            # docstring_section_style: list
            # filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: false
            separate_signature: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            extensions:
            # - griff_fieldz: https://github.com/pyapp-kit/griffe-fieldz
            - griffe_pydantic:
                schema: false