"""mlp_pipeline.py.

Last Updated: April 15, 2026
Last Tested: TBD.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd
import scipy.sparse as sp
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import StandardScaler

try:
    from imblearn.over_sampling import SMOTE
except ImportError:  # pragma: no cover - optional dependency
    SMOTE = None

from lexos.classification.trainer import fit_classifier
from lexos.dtm import DTM
from lexos.tokenizer import WhitespaceTokenizer
from lexos.tokenizer.ngrams import Ngrams


@dataclass(slots=True)
class MLPPipelineConfig:
    """Configuration for a leakage-safe MLP text classification pipeline."""

    seed: int = 42
    min_df: int = 2
    test_size: float = 0.2
    cv_splits: int = 5
    include_bigrams: bool = True
    use_corpus_stats_features: bool = False
    corpus_stats_feature_columns: tuple[str, ...] | None = None
    use_smote: bool = True
    mlp_kwargs: dict[str, Any] = field(
        default_factory=lambda: {
            "hidden_layer_sizes": (64,),
            "activation": "relu",
            "solver": "adam",
            "alpha": 1e-4,
            "learning_rate_init": 1e-3,
            "max_iter": 1000,
        }
    )


@dataclass(slots=True)
class MLPPipelineResult:
    """Container for outputs generated by `run_mlp_authorship_pipeline()`."""

    holdout_report: pd.DataFrame
    holdout_confusion_matrix: pd.DataFrame
    holdout_metrics: dict[str, float]
    cv_fold_metrics: pd.DataFrame
    cv_mean_metrics: dict[str, float]
    test_predictions: pd.DataFrame
    final_model: Any
    final_dtm: DTM
    final_scaler: StandardScaler


def _tokenize_items(
    items: Sequence[str | Sequence[str]],
    include_bigrams: bool = True,
) -> list[list[str]]:
    """Tokenize text items to lowercase alphabetic unigrams and optional bigrams.

    Each item can be either:
    - a raw text string, or
    - an iterable of pre-tokenized strings.
    """
    ws_tokenizer = WhitespaceTokenizer()
    ngrams = Ngrams(n=2)
    token_lists: list[list[str]] = []

    for item in items:
        if isinstance(item, str):
            unigrams = [tok for tok in ws_tokenizer(item.lower()) if tok.isalpha()]
        else:
            unigrams = [str(tok).lower() for tok in item if str(tok).isalpha()]

        if include_bigrams:
            bigrams = [
                f"{t1}_{t2}"
                for t1, t2 in ngrams.from_tokens(unigrams, output="tuples")
                if t1.isalpha() and t2.isalpha()
            ]
            tokens = unigrams + bigrams
        else:
            tokens = unigrams

        token_lists.append(tokens)

    if any(len(tokens) == 0 for tokens in token_lists):
        raise ValueError("At least one document produced zero tokens after preprocessing.")

    return token_lists


def _to_dense(matrix: Any) -> np.ndarray:
    """Convert sparse or dense matrices to a dense NumPy array."""
    return matrix.toarray() if hasattr(matrix, "toarray") else np.asarray(matrix)


def _apply_smote(
    feature_matrix: Any,
    labels: np.ndarray,
    seed: int,
    enabled: bool,
) -> tuple[np.ndarray, np.ndarray]:
    """Apply SMOTE to a feature matrix and labels when enabled."""
    dense_matrix = _to_dense(feature_matrix)
    if not enabled:
        return dense_matrix, labels

    if SMOTE is None:
        raise ImportError(
            "SMOTE requested, but imbalanced-learn is not installed. "
            "Install it with `pip install imbalanced-learn` or set `use_smote=False`."
        )

    smote = SMOTE(random_state=seed)
    return smote.fit_resample(dense_matrix, labels)


def _build_corpus_stats_features(
    token_lists: Sequence[Sequence[str]],
    doc_ids: Sequence[str],
    config: MLPPipelineConfig,
) -> pd.DataFrame:
    """Build an aligned CorpusStats feature frame for a batch of documents."""
    try:
        from lexos.corpus.corpus_stats import CorpusStats
    except ImportError as exc:
        raise ImportError(
            "CorpusStats features were requested, but optional dependencies are missing. "
            "Install spacytextblob (and the corpus stats dependencies) or set "
            "use_corpus_stats_features=False."
        ) from exc

    docs_for_corpus: list[tuple[str, str, str]] = []
    for doc_id, tokens in zip(doc_ids, token_lists):
        if isinstance(tokens, str):
            doc_input = tokens
        else:
            # tokens is a sequence of token strings; join into text
            doc_input = " ".join(tokens)
        docs_for_corpus.append((doc_id, doc_id, doc_input))

    corpus = CorpusStats(
        docs=docs_for_corpus,
        min_df=config.min_df,
    )

    stats_df = corpus.doc_stats_df.reindex(doc_ids)
    if stats_df.isnull().all(axis=1).any():
        missing_docs = stats_df.index[stats_df.isnull().all(axis=1)].tolist()
        raise ValueError(f"CorpusStats could not align features for: {missing_docs}")

    if config.corpus_stats_feature_columns is None:
        selected = stats_df.select_dtypes(include=[np.number]).copy()
    else:
        missing_columns = [
            column
            for column in config.corpus_stats_feature_columns
            if column not in stats_df.columns
        ]
        if missing_columns:
            raise ValueError(
                "Unknown CorpusStats feature column(s): "
                + ", ".join(missing_columns)
            )
        selected = stats_df.loc[:, list(config.corpus_stats_feature_columns)].copy()

    return selected.fillna(0.0)


def _build_feature_matrix(
    token_lists: Sequence[Sequence[str]],
    doc_labels: Sequence[str],
    config: MLPPipelineConfig,
) -> tuple[Any, DTM, pd.DataFrame | None]:
    """Build the model feature matrix and optional CorpusStats features."""
    dtm = DTM()
    x_dtm = dtm.fit_transform(token_lists, labels=list(doc_labels), min_df=config.min_df)

    if not config.use_corpus_stats_features:
        return x_dtm, dtm, None

    corpus_stats_features = _build_corpus_stats_features(token_lists, doc_labels, config)
    x_meta = sp.csr_matrix(corpus_stats_features.to_numpy(dtype=float, copy=True))
    x_features = sp.hstack([x_dtm, x_meta], format="csr")
    return x_features, dtm, corpus_stats_features


def run_mlp_authorship_pipeline(
    train_data: Sequence[str | Sequence[str]],
    train_labels: Sequence[str],
    test_data: Sequence[str | Sequence[str]] | None = None,
    test_ids: Sequence[str] | None = None,
    config: MLPPipelineConfig | None = None,
) -> MLPPipelineResult:
    """Run a leakage-safe MLP text-classification pipeline.

    The workflow follows this sequence:
    1. Tokenize training items into alphabetic unigrams plus optional bigrams.
    2. Optionally build CorpusStats features and append them to the DTM.
    3. Holdout split training docs, then fit features/scaler on train only.
    4. Train and evaluate an MLP on holdout data.
    5. Run leakage-safe stratified cross-validation over all labeled docs.
    6. Refit on all labeled docs and infer labels for test_data, if provided.

    Args:
        train_data: Labeled training samples as raw text or token lists.
        train_labels: Labels corresponding to train_data.
        test_data: Optional unlabeled samples for inference as raw text or token lists.
        test_ids: Optional IDs/names for test_data rows.
        config: Optional configuration object.

    Returns:
        MLPPipelineResult: Structured outputs for holdout/CV/inference stages.
    """
    cfg = config or MLPPipelineConfig()
    np.random.seed(cfg.seed)

    if len(train_data) == 0:
        raise ValueError("train_data must contain at least one sample.")
    if len(train_data) != len(train_labels):
        raise ValueError("train_data and train_labels must have matching lengths.")
    if test_data is not None and test_ids is not None and len(test_data) != len(test_ids):
        raise ValueError("test_data and test_ids must have matching lengths.")

    all_token_lists = _tokenize_items(train_data, include_bigrams=cfg.include_bigrams)
    test_token_lists = (
        _tokenize_items(test_data, include_bigrams=cfg.include_bigrams)
        if test_data is not None
        else None
    )

    all_doc_labels = [f"train_doc_{i}" for i in range(len(all_token_lists))]
    y = np.asarray(train_labels)
    indices = np.arange(len(all_token_lists))

    train_idx, test_idx = train_test_split(
        indices,
        test_size=cfg.test_size,
        random_state=cfg.seed,
        stratify=y,
        shuffle=True,
    )

    token_train = [all_token_lists[i] for i in train_idx]
    token_test = [all_token_lists[i] for i in test_idx]
    doc_labels_train = [all_doc_labels[i] for i in train_idx]
    y_train = y[train_idx]
    y_test = y[test_idx]

    x_train, dtm_holdout, _ = _build_feature_matrix(token_train, doc_labels_train, cfg)
    x_test = dtm_holdout.transform(token_test)
    if cfg.use_corpus_stats_features:
        holdout_test_features = _build_corpus_stats_features(token_test, [f"holdout_test_{i}" for i in range(len(token_test))], cfg)
        x_test = sp.hstack(
            [x_test, sp.csr_matrix(holdout_test_features.to_numpy(dtype=float, copy=True))],
            format="csr",
        )

    scaler_holdout = StandardScaler(with_mean=False)
    x_train_scaled = scaler_holdout.fit_transform(x_train)
    x_test_scaled = scaler_holdout.transform(x_test)

    x_train_model, y_train_model = _apply_smote(x_train_scaled, y_train, cfg.seed, cfg.use_smote)
    holdout_model = fit_classifier(
        feature_matrix=x_train_model,
        target_labels=y_train_model,
        model="mlp",
        random_state=cfg.seed,
        **cfg.mlp_kwargs,
    )

    y_pred = holdout_model.predict(_to_dense(x_test_scaled))
    holdout_metrics = {
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        "macro_f1": float(f1_score(y_test, y_pred, average="macro")),
    }

    report_dict = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    holdout_report = pd.DataFrame(report_dict).T

    class_labels = sorted(np.unique(y).tolist())
    cm = confusion_matrix(y_test, y_pred, labels=class_labels)
    holdout_confusion_matrix = pd.DataFrame(
        cm,
        index=[f"true_{label}" for label in class_labels],
        columns=[f"pred_{label}" for label in class_labels],
    )

    cv = StratifiedKFold(n_splits=cfg.cv_splits, shuffle=True, random_state=cfg.seed)
    cv_rows: list[dict[str, float]] = []

    for fold, (tr_idx, va_idx) in enumerate(cv.split(all_token_lists, y), start=1):
        fold_train_tokens = [all_token_lists[i] for i in tr_idx]
        fold_valid_tokens = [all_token_lists[i] for i in va_idx]
        fold_train_doc_labels = [all_doc_labels[i] for i in tr_idx]
        y_tr = y[tr_idx]
        y_va = y[va_idx]

        x_tr, dtm_fold, _ = _build_feature_matrix(fold_train_tokens, fold_train_doc_labels, cfg)
        x_va = dtm_fold.transform(fold_valid_tokens)
        if cfg.use_corpus_stats_features:
            fold_valid_features = _build_corpus_stats_features(
                fold_valid_tokens,
                [f"fold_{fold}_valid_{i}" for i in range(len(fold_valid_tokens))],
                cfg,
            )
            x_va = sp.hstack(
                [x_va, sp.csr_matrix(fold_valid_features.to_numpy(dtype=float, copy=True))],
                format="csr",
            )

        scaler_fold = StandardScaler(with_mean=False)
        x_tr_scaled = scaler_fold.fit_transform(x_tr)
        x_va_scaled = scaler_fold.transform(x_va)

        x_tr_model, y_tr_model = _apply_smote(x_tr_scaled, y_tr, cfg.seed, cfg.use_smote)
        fold_model = fit_classifier(
            feature_matrix=x_tr_model,
            target_labels=y_tr_model,
            model="mlp",
            random_state=cfg.seed,
            **cfg.mlp_kwargs,
        )

        fold_pred = fold_model.predict(_to_dense(x_va_scaled))
        cv_rows.append(
            {
                "fold": float(fold),
                "accuracy": float(accuracy_score(y_va, fold_pred)),
                "balanced_accuracy": float(balanced_accuracy_score(y_va, fold_pred)),
                "macro_f1": float(f1_score(y_va, fold_pred, average="macro")),
            }
        )

    cv_fold_metrics = pd.DataFrame(cv_rows)
    cv_mean_metrics = {
        "accuracy": float(cv_fold_metrics["accuracy"].mean()),
        "balanced_accuracy": float(cv_fold_metrics["balanced_accuracy"].mean()),
        "macro_f1": float(cv_fold_metrics["macro_f1"].mean()),
    }

    x_full, dtm_final, _ = _build_feature_matrix(all_token_lists, all_doc_labels, cfg)

    scaler_final = StandardScaler(with_mean=False)
    x_full_scaled = scaler_final.fit_transform(x_full)

    x_full_model, y_full_model = _apply_smote(x_full_scaled, y, cfg.seed, cfg.use_smote)
    final_model = fit_classifier(
        feature_matrix=x_full_model,
        target_labels=y_full_model,
        model="mlp",
        random_state=cfg.seed,
        **cfg.mlp_kwargs,
    )

    if test_token_lists is not None:
        x_test_infer = dtm_final.transform(test_token_lists)
        if cfg.use_corpus_stats_features:
            test_feature_ids = list(test_ids) if test_ids is not None else [f"test_doc_{i}" for i in range(len(test_token_lists))]
            test_stats_features = _build_corpus_stats_features(test_token_lists, test_feature_ids, cfg)
            x_test_infer = sp.hstack(
                [x_test_infer, sp.csr_matrix(test_stats_features.to_numpy(dtype=float, copy=True))],
                format="csr",
            )
        x_test_infer_scaled = scaler_final.transform(x_test_infer)
        test_pred = final_model.predict(_to_dense(x_test_infer_scaled))

        if test_ids is None:
            sample_ids = [f"test_doc_{i}" for i in range(len(test_pred))]
        else:
            sample_ids = list(test_ids)

        test_predictions = pd.DataFrame(
            {
                "sample_id": sample_ids,
                "predicted_label": test_pred,
            }
        )

        if hasattr(final_model, "predict_proba"):
            proba = final_model.predict_proba(_to_dense(x_test_infer_scaled))
            for idx, label in enumerate(final_model.classes_):
                safe_label = str(label).lower().replace(" ", "_")
                test_predictions[f"p_{safe_label}"] = proba[:, idx]
    else:
        test_predictions = pd.DataFrame(columns=["sample_id", "predicted_label"])

    return MLPPipelineResult(
        holdout_report=holdout_report,
        holdout_confusion_matrix=holdout_confusion_matrix,
        holdout_metrics=holdout_metrics,
        cv_fold_metrics=cv_fold_metrics,
        cv_mean_metrics=cv_mean_metrics,
        test_predictions=test_predictions,
        final_model=final_model,
        final_dtm=dtm_final,
        final_scaler=scaler_final,
    )


def save_mlp_unknown_predictions(results: MLPPipelineResult, output_csv: Path | str) -> Path:
    """Save test-set predictions from a pipeline result to CSV."""
    output_path = Path(output_csv).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    results.test_predictions.to_csv(output_path, index=False)
    return output_path


__all__ = [
    "MLPPipelineConfig",
    "MLPPipelineResult",
    "run_mlp_authorship_pipeline",
    "save_mlp_unknown_predictions",
]